version: '3.1'
services:
  db_web:
    image: postgres:9.6.3
    environment:
      - POSTGRES_USER=ocl
      - POSTGRES_PASSWORD=Ocl123
    volumes:
      - db_web_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db_web
    links:
      - "db_web:dbweb.openconceptlab.org"
    external_links:
      - "ocl_api:api.openconceptlab.org"
    ports:
      - "7000:7000"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgres://ocl:Ocl123@dbweb.openconceptlab.org:5432/ocl
      - OCL_API_HOST=http://api.openconceptlab.org:8000
      - OCL_API_TOKEN=65d5a5012b608cb60d10d535e003e2b36e1d3201
      - OCL_ANON_API_TOKEN=65d5a5012b608cb60d10d535e003e2b36e1d3201
      - ROOT_PWD=Root123
volumes:
  db_web_data:
networks:
  default:
    external:
      name: ocl_default
