version: '2.0'
services:
  db_web:
    ports:
      - "5432:5432"
  web:
    build:
      dockerfile: Dockerfile-dev
    command: bash docker-startup-dev.sh
    volumes:
      - .:/code
    ports:
      #ports for debugging
      - "7001:7001"
      - "2001:22"