version: '2.1'
services:
  db_web:
    ports:
      - "5432:5432"
  web:
    image: openconceptlab/oclweb:dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/code
    ports:
      #ports for debugging
      - "7001:7001"
      - "2001:22"
    environment:
      - SSH=true